#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ def ingressgateway_service_nodeport():
#@overlay/match by=overlay.subset({"kind":"Service","metadata":{"name":"istio-ingressgateway"}})
---
spec:
  #@overlay/replace
  type: NodePort
#@ end
