#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

#@ load("/namespaces.star", "system_namespace", "workloads_namespace")

#@ def ingress_values():
system_namespace: #@ system_namespace()
workloads_namespace: #@ workloads_namespace()
system_domain: #@ data.values.system_domain
app_domains:
#@ for domain in data.values.app_domains:
#@overlay/append
- #@ domain
#@ end
gateway:
  https_only: #@ data.values.gateway.https_only
system_certificate:
  crt: #@ data.values.system_certificate.crt
  key: #@ data.values.system_certificate.key
  ca: #@ data.values.system_certificate.ca

workloads_certificate:
  crt: #@ data.values.workloads_certificate.crt
  key: #@ data.values.workloads_certificate.key
  ca: #@ data.values.workloads_certificate.ca
load_balancer:
  static_ip: #@ data.values.load_balancer.static_ip
#@ end

#@ if data.values.networking.ingress_solution_provider == "istio":
#@ istio = library.get("istio").with_data_values(ingress_values())

#! --- #@ template.replace(istio.with_data_values(ingress_values()).eval()) # TODO investigate for non-overlay comrades

#@   overlays = istio.export("all_overlays", path="all-overlays.star")
#@   for overlay in overlays:
--- #@ template.replace(overlay())
#@   end

#@ conditional_overlays = istio.export("conditional_overlays", path="all-overlays.star")

#@ if not data.values.load_balancer.enable:
--- #@ template.replace(conditional_overlays["ingressgateway_service_nodeport"]())
#@ end

#@ if data.values.remove_resource_requirements:
--- #@ template.replace(conditional_overlays["remove_resource_requirements"]())
#@ end

#@ if data.values.use_external_dns_for_wildcard:
--- #@ template.replace(conditional_overlays["use_external_dns_for_wildcard"]())
#@ end

#@ if data.values.use_first_party_jwt_tokens:
--- #@ template.replace(conditional_overlays["use_first_party_jwt_tokens"]())
#@ end

#@ end

