#@ load("@ytt:overlay", "overlay")

#@ def label_istio_ns():
#@overlay/match by=overlay.subset({"kind":"Namespace", "metadata":{"name": "istio-system"}})
---
metadata:
  #@overlay/match missing_ok=True
  labels:
    #@overlay/match missing_ok=True
    cf-for-k8s.cloudfoundry.org/istio-system-ns: ""
#@ end
